version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/react-component

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/react-component

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/react-component
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm test
  dist:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build
      - run: node ./scripts/dekko-dist.js
      - persist_to_workspace:
          root: ~/react-component
          paths:
            - dist
  compile:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run compile
      - run: node ./scripts/dekko-lib.js
      - persist_to_workspace:
          root: ~/react-component
          paths:
            - lib
  test_dist:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          command: npm test -- -u
          environment:
            LIB_DIR: dist
  test_lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          command: npm test -- -u
          environment:
            LIB_DIR: lib

workflows:
  version: 2
  build:
    jobs:
      - setup
      - dist:
          requires:
            - setup
      - compile:
          requires:
            - setup
      - test_dist:
          requires:
            - dist
      - test_lib:
          requires:
            - compile
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
